export default {
  copyright:
    'Copyright 2022 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt',
  totalItems: 6,
  totalEvents: 0,
  totalGames: 6,
  totalGamesInProgress: 0,
  dates: [
    {
      date: '2022-07-21',
      totalItems: 6,
      totalEvents: 0,
      totalGames: 6,
      totalGamesInProgress: 0,
      games: [
        {
          gamePk: 662776,
          link: '/api/v1.1/game/662776/feed/live',
          gameType: 'R',
          season: '2022',
          gameDate: '2022-07-21T17:10:00Z',
          officialDate: '2022-07-21',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 147,
                name: 'New York Yankees',
                link: '/api/v1/teams/147',
              },
              splitSquad: false,
              seriesNumber: 31,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 117,
                name: 'Houston Astros',
                link: '/api/v1/teams/117',
              },
              splitSquad: false,
              seriesNumber: 31,
            },
          },
          venue: {
            id: 2392,
            name: 'Minute Maid Park',
            link: '/api/v1/venues/2392',
          },
          content: {
            link: '/api/v1/game/662776/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'S',
          gamedayType: 'P',
          tiebreaker: 'N',
          calendarEventID: '14-662776-2022-07-21',
          seasonDisplay: '2022',
          dayNight: 'day',
          description: 'Rescheduled from 4/5',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 2,
          seriesGameNumber: 1,
          seriesDescription: 'Regular Season',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 662775,
          link: '/api/v1.1/game/662775/feed/live',
          gameType: 'R',
          season: '2022',
          gameDate: '2022-07-21T22:40:00Z',
          officialDate: '2022-07-21',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 147,
                name: 'New York Yankees',
                link: '/api/v1/teams/147',
              },
              splitSquad: false,
              seriesNumber: 31,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 117,
                name: 'Houston Astros',
                link: '/api/v1/teams/117',
              },
              splitSquad: false,
              seriesNumber: 31,
            },
          },
          venue: {
            id: 2392,
            name: 'Minute Maid Park',
            link: '/api/v1/venues/2392',
          },
          content: {
            link: '/api/v1/game/662775/content',
          },
          gameNumber: 2,
          publicFacing: true,
          doubleHeader: 'S',
          gamedayType: 'P',
          tiebreaker: 'N',
          calendarEventID: '14-662775-2022-07-21',
          seasonDisplay: '2022',
          dayNight: 'night',
          description: 'Rescheduled from 4/6',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 2,
          seriesGameNumber: 2,
          seriesDescription: 'Regular Season',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },

        {
          gamePk: 661421,
          link: '/api/v1.1/game/661421/feed/live',
          gameType: 'R',
          season: '2022',
          gameDate: '2022-07-21T17:10:00Z',
          officialDate: '2022-07-21',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 140,
                name: 'Texas Rangers',
                link: '/api/v1/teams/140',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 146,
                name: 'Miami Marlins',
                link: '/api/v1/teams/146',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
          },
          venue: {
            id: 4169,
            name: 'loanDepot park',
            link: '/api/v1/venues/4169',
          },
          content: {
            link: '/api/v1/game/661421/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'P',
          tiebreaker: 'N',
          calendarEventID: '14-661421-2022-07-21',
          seasonDisplay: '2022',
          dayNight: 'day',
          description: 'Rescheduled from 4/4',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Regular Season',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 662411,
          link: '/api/v1.1/game/662411/feed/live',
          gameType: 'R',
          season: '2022',
          gameDate: '2022-07-21T19:37:00Z',
          officialDate: '2022-07-21',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 116,
                name: 'Detroit Tigers',
                link: '/api/v1/teams/116',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 133,
                name: 'Oakland Athletics',
                link: '/api/v1/teams/133',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
          },
          venue: {
            id: 10,
            name: 'Oakland Coliseum',
            link: '/api/v1/venues/10',
          },
          content: {
            link: '/api/v1/game/662411/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'Y',
          gamedayType: 'P',
          tiebreaker: 'N',
          calendarEventID: '14-662411-2022-07-21',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 2,
          seriesGameNumber: 1,
          seriesDescription: 'Regular Season',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 662408,
          link: '/api/v1.1/game/662408/feed/live',
          gameType: 'R',
          season: '2022',
          gameDate: '2022-07-21T16:42:00Z',
          officialDate: '2022-07-21',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: true,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 116,
                name: 'Detroit Tigers',
                link: '/api/v1/teams/116',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 133,
                name: 'Oakland Athletics',
                link: '/api/v1/teams/133',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
          },
          venue: {
            id: 10,
            name: 'Oakland Coliseum',
            link: '/api/v1/venues/10',
          },
          content: {
            link: '/api/v1/game/662408/content',
          },
          gameNumber: 2,
          publicFacing: true,
          doubleHeader: 'Y',
          gamedayType: 'P',
          tiebreaker: 'N',
          calendarEventID: '14-662408-2022-07-21',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 2,
          seriesGameNumber: 2,
          seriesDescription: 'Regular Season',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 662685,
          link: '/api/v1.1/game/662685/feed/live',
          gameType: 'R',
          season: '2022',
          gameDate: '2022-07-22T02:09:00Z',
          officialDate: '2022-07-21',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 137,
                name: 'San Francisco Giants',
                link: '/api/v1/teams/137',
              },
              splitSquad: false,
              seriesNumber: 31,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 119,
                name: 'Los Angeles Dodgers',
                link: '/api/v1/teams/119',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
          },
          venue: {
            id: 22,
            name: 'Dodger Stadium',
            link: '/api/v1/venues/22',
          },
          content: {
            link: '/api/v1/game/662685/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'P',
          tiebreaker: 'N',
          calendarEventID: '14-662685-2022-07-21',
          seasonDisplay: '2022',
          dayNight: 'night',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 4,
          seriesGameNumber: 1,
          seriesDescription: 'Regular Season',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
      ],
      events: [],
    },
  ],
};
