export default {
  copyright:
    'Copyright 2022 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt',
  totalItems: 14,
  totalEvents: 0,
  totalGames: 14,
  totalGamesInProgress: 0,
  dates: [
    {
      date: '2022-03-31',
      totalItems: 14,
      totalEvents: 0,
      totalGames: 14,
      totalGamesInProgress: 0,
      games: [
        {
          gamePk: 706831,
          link: '/api/v1.1/game/706831/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-04-01T01:40:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 2,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 114,
                name: 'Cleveland Guardians',
                link: '/api/v1/teams/114',
              },
              splitSquad: false,
              seriesNumber: 14,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 136,
                name: 'Seattle Mariners',
                link: '/api/v1/teams/136',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2530,
            name: 'Peoria Stadium',
            link: '/api/v1/venues/2530',
          },
          content: {
            link: '/api/v1/game/706831/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-706831-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'night',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706856,
          link: '/api/v1.1/game/706856/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T17:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 1,
                pct: '.000',
              },
              team: {
                id: 110,
                name: 'Baltimore Orioles',
                link: '/api/v1/teams/110',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
            home: {
              leagueRecord: {
                wins: 2,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 134,
                name: 'Pittsburgh Pirates',
                link: '/api/v1/teams/134',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2526,
            name: 'LECOM Park',
            link: '/api/v1/venues/2526',
          },
          content: {
            link: '/api/v1/game/706856/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'E',
          tiebreaker: 'N',
          calendarEventID: '14-706856-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 707016,
          link: '/api/v1.1/game/707016/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T17:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 3,
                pct: '.000',
              },
              team: {
                id: 142,
                name: 'Minnesota Twins',
                link: '/api/v1/teams/142',
              },
              splitSquad: false,
              seriesNumber: 14,
            },
            home: {
              leagueRecord: {
                wins: 3,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 111,
                name: 'Boston Red Sox',
                link: '/api/v1/teams/111',
              },
              splitSquad: false,
              seriesNumber: 14,
            },
          },
          venue: {
            id: 4309,
            name: 'JetBlue Park',
            link: '/api/v1/venues/4309',
          },
          content: {
            link: '/api/v1/game/707016/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-707016-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 707035,
          link: '/api/v1.1/game/707035/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T17:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 1,
                pct: '.000',
              },
              team: {
                id: 139,
                name: 'Tampa Bay Rays',
                link: '/api/v1/teams/139',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
            home: {
              leagueRecord: {
                wins: 2,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 144,
                name: 'Atlanta Braves',
                link: '/api/v1/teams/144',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 5380,
            name: 'CoolToday Park',
            link: '/api/v1/venues/5380',
          },
          content: {
            link: '/api/v1/game/707035/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-707035-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706864,
          link: '/api/v1.1/game/706864/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T17:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 1,
                pct: '.000',
              },
              team: {
                id: 147,
                name: 'New York Yankees',
                link: '/api/v1/teams/147',
              },
              splitSquad: false,
              seriesNumber: 14,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 143,
                name: 'Philadelphia Phillies',
                link: '/api/v1/teams/143',
              },
              splitSquad: false,
              seriesNumber: 14,
            },
          },
          venue: {
            id: 2700,
            name: 'BayCare Ballpark',
            link: '/api/v1/venues/2700',
          },
          content: {
            link: '/api/v1/game/706864/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'E',
          tiebreaker: 'N',
          calendarEventID: '14-706864-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706795,
          link: '/api/v1.1/game/706795/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T17:07:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 1,
                pct: '.000',
              },
              team: {
                id: 116,
                name: 'Detroit Tigers',
                link: '/api/v1/teams/116',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 141,
                name: 'Toronto Blue Jays',
                link: '/api/v1/teams/141',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2536,
            name: 'TD Ballpark',
            link: '/api/v1/venues/2536',
          },
          content: {
            link: '/api/v1/game/706795/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'E',
          tiebreaker: 'N',
          calendarEventID: '14-706795-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706871,
          link: '/api/v1.1/game/706871/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T20:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 0,
                pct: '.000',
              },
              team: {
                id: 118,
                name: 'Kansas City Royals',
                link: '/api/v1/teams/118',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 133,
                name: 'Oakland Athletics',
                link: '/api/v1/teams/133',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2507,
            name: 'Hohokam Stadium',
            link: '/api/v1/venues/2507',
          },
          content: {
            link: '/api/v1/game/706871/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-706871-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706841,
          link: '/api/v1.1/game/706841/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T20:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 2,
                losses: 1,
                pct: '.667',
              },
              team: {
                id: 115,
                name: 'Colorado Rockies',
                link: '/api/v1/teams/115',
              },
              splitSquad: false,
              seriesNumber: 33,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 137,
                name: 'San Francisco Giants',
                link: '/api/v1/teams/137',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2532,
            name: 'Scottsdale Stadium',
            link: '/api/v1/venues/2532',
          },
          content: {
            link: '/api/v1/game/706841/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-706841-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706802,
          link: '/api/v1.1/game/706802/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T20:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 1,
                pct: '.000',
              },
              team: {
                id: 119,
                name: 'Los Angeles Dodgers',
                link: '/api/v1/teams/119',
              },
              splitSquad: false,
              seriesNumber: 14,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 1,
                pct: '.000',
              },
              team: {
                id: 140,
                name: 'Texas Rangers',
                link: '/api/v1/teams/140',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2603,
            name: 'Surprise Stadium',
            link: '/api/v1/venues/2603',
          },
          content: {
            link: '/api/v1/game/706802/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-706802-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 707047,
          link: '/api/v1.1/game/707047/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T20:10:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 135,
                name: 'San Diego Padres',
                link: '/api/v1/teams/135',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
            home: {
              leagueRecord: {
                wins: 0,
                losses: 3,
                pct: '.000',
              },
              team: {
                id: 109,
                name: 'Arizona Diamondbacks',
                link: '/api/v1/teams/109',
              },
              splitSquad: false,
              seriesNumber: 33,
            },
          },
          venue: {
            id: 4249,
            name: 'Salt River Fields at Talking Stick',
            link: '/api/v1/venues/4249',
          },
          content: {
            link: '/api/v1/game/707047/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'E',
          tiebreaker: 'N',
          calendarEventID: '14-707047-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706909,
          link: '/api/v1.1/game/706909/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T20:10:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 108,
                name: 'Los Angeles Angels',
                link: '/api/v1/teams/108',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 158,
                name: 'Milwaukee Brewers',
                link: '/api/v1/teams/158',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 2518,
            name: 'American Family Fields of Phoenix',
            link: '/api/v1/venues/2518',
          },
          content: {
            link: '/api/v1/game/706909/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-706909-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'day',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706892,
          link: '/api/v1.1/game/706892/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T22:10:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 0,
                losses: 2,
                pct: '.000',
              },
              team: {
                id: 120,
                name: 'Washington Nationals',
                link: '/api/v1/teams/120',
              },
              splitSquad: false,
              seriesNumber: 12,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 121,
                name: 'New York Mets',
                link: '/api/v1/teams/121',
              },
              splitSquad: false,
              seriesNumber: 11,
            },
          },
          venue: {
            id: 2856,
            name: 'Clover Park',
            link: '/api/v1/venues/2856',
          },
          content: {
            link: '/api/v1/game/706892/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'E',
          tiebreaker: 'N',
          calendarEventID: '14-706892-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'night',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706917,
          link: '/api/v1.1/game/706917/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-03-31T22:40:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 1,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 138,
                name: 'St. Louis Cardinals',
                link: '/api/v1/teams/138',
              },
              splitSquad: false,
              seriesNumber: 11,
            },
            home: {
              leagueRecord: {
                wins: 2,
                losses: 0,
                pct: '1.000',
              },
              team: {
                id: 146,
                name: 'Miami Marlins',
                link: '/api/v1/teams/146',
              },
              splitSquad: false,
              seriesNumber: 11,
            },
          },
          venue: {
            id: 2520,
            name: 'Roger Dean Chevrolet Stadium',
            link: '/api/v1/venues/2520',
          },
          content: {
            link: '/api/v1/game/706917/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'E',
          tiebreaker: 'N',
          calendarEventID: '14-706917-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'night',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
        {
          gamePk: 706991,
          link: '/api/v1.1/game/706991/feed/live',
          gameType: 'S',
          season: '2022',
          gameDate: '2022-04-01T01:05:00Z',
          officialDate: '2022-03-31',
          status: {
            abstractGameState: 'Preview',
            codedGameState: 'S',
            detailedState: 'Scheduled',
            statusCode: 'S',
            startTimeTBD: false,
            abstractGameCode: 'P',
          },
          teams: {
            away: {
              leagueRecord: {
                wins: 2,
                losses: 1,
                pct: '.667',
              },
              team: {
                id: 145,
                name: 'Chicago White Sox',
                link: '/api/v1/teams/145',
              },
              splitSquad: false,
              seriesNumber: 30,
            },
            home: {
              leagueRecord: {
                wins: 1,
                losses: 1,
                pct: '.500',
              },
              team: {
                id: 113,
                name: 'Cincinnati Reds',
                link: '/api/v1/teams/113',
              },
              splitSquad: false,
              seriesNumber: 13,
            },
          },
          venue: {
            id: 3834,
            name: 'Goodyear Ballpark',
            link: '/api/v1/venues/3834',
          },
          content: {
            link: '/api/v1/game/706991/content',
          },
          gameNumber: 1,
          publicFacing: true,
          doubleHeader: 'N',
          gamedayType: 'N',
          tiebreaker: 'N',
          calendarEventID: '14-706991-2022-03-31',
          seasonDisplay: '2022',
          dayNight: 'night',
          scheduledInnings: 9,
          reverseHomeAwayStatus: false,
          inningBreakLength: 120,
          gamesInSeries: 1,
          seriesGameNumber: 1,
          seriesDescription: 'Spring Training',
          recordSource: 'S',
          ifNecessary: 'N',
          ifNecessaryDescription: 'Normal Game',
        },
      ],
      events: [],
    },
  ],
};
